#
# Sass lint configuration, https://www.npmjs.com/package/sass-lint.
#

files:
  include: "src/*.scss"

# https://github.com/sasstools/sass-lint/tree/master/docs/rules
rules:
  quotes:
    - 2
    -
      style: double
